[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
via_ir = true
optimizer = true
optimizer_runs = 200

# Path remappings
remappings = [
    "@src/=src/",
    "@script/=script/",
    "@test/=test/"
]

ffi = true
fs_permissions = [
    { access = "read-write", path = "./script/config/local-dev.json" },
]
evm_version = 'cancun'
gas_limit = "300000000"
bytecode_hash = "none"

# added due to v1.0 foundry
# ref: https://book.getfoundry.sh/guides/v1.0-migration#expect-revert-cheatcode-disabled-on-internal-calls-by-default
allow_internal_expect_revert = true

[fuzz]
runs = 5 # change this for higher number of fuzz runs locally

[profile.ci.fuzz]
runs = 10000

[profile.ci.invariant]
runs = 1000            # The number of calls to make in the invariant tests
call_override = false  # Override calls
fail_on_revert = false # Fail the test if the contract reverts

[profile.ci_main.fuzz]
runs = 100000

[profile.ci_main.invariant]
runs = 10000           # The number of calls to make in the invariant tests
call_override = false  # Override calls
fail_on_revert = false # Fail the test if the contract reverts


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
